Args = --enable-native-access=ALL-UNNAMED \
       --initialize-at-run-time=dev.ivchenko.lwjwae.foreign.NativeLibraries,dev.ivchenko.lwjwae.gtk4.binding.Glib,dev.ivchenko.lwjwae.gtk4.binding.Gtk,dev.ivchenko.lwjwae.gtk4.binding.WebKit,dev.ivchenko.lwjwae.gtk4.Gtk4Dispatcher,dev.ivchenko.lwjwae.gtk4.Gtk4Window,dev.ivchenko.lwjwae.gtk4.Gtk4Application
