Args = --enable-native-access=ALL-UNNAMED \
       --initialize-at-run-time=dev.ivchenko.lwjwae.foreign.NativeLibraries,dev.ivchenko.lwjwae.gtk.binding.Glib,dev.ivchenko.lwjwae.gtk.binding.Gtk,dev.ivchenko.lwjwae.gtk.binding.WebKit,dev.ivchenko.lwjwae.gtk.GtkDispatcher,dev.ivchenko.lwjwae.gtk.GtkWindow,dev.ivchenko.lwjwae.gtk.GtkApplication
